### ISSUE TITLE
TODO w/c 2016-08-22

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#489]
Priorities this week:

@octopusinvitro + @ondenman 
- [x] Header links broken: https://github.com/everypolitician/viewer-sinatra/issues/14816
- [x] Templates work with objects, not JSON (https://github.com/everypolitician/viewer-sinatra/issues/14844)
  - [x] `countries.erb` <s>(2)</s>  
  - [x] `country.erb` <s>(8)</s> 
  - [x] `country_download.erb` <s>(19)</s>  (1)
  - [x] `country_selector.erb` <s>(5)</s>
  - [x] `homepage.erb` <s>(1)</s> 
  - [x] `house_wikidata.erb` <s>(1)</s>  
  - [x] `layout.erb` (3)
  - [x] `needed.erb` <s>(9)</s>
  - [x] `spider_base.erb` <s>(1)</s> 
  - [x] `term_table.erb` (61)

@chrismytton 
- [x] Uganda Scraper https://github.com/everypolitician/everypolitician-data/issues/15883
  - [x] Fix it for the 9th term
  - [x] Add scraped_page_archive to it
  - [x] Make it work for other terms
- [ ] Uganda Areas https://github.com/everypolitician/everypolitician-data/pull/12496
- [ ] Group UUIDs https://github.com/everypolitician/everypolitician/issues/428

@davewhiteland 
- [ ] Document Libraries https://github.com/everypolitician/everypolitician-docs/issues/23
- [ ] READMEs 
  - [ ] https://github.com/everypolitician/everypolitician-popolo/issues/33
  - [ ] https://github.com/everypolitician/everypolitician-ruby/issues/15
- [x] Repo Descriptions: https://github.com/everypolitician/everypolitician/issues/454
  - [x] https://github.com/everypolitician/everypolitician-ruby
  - [x] https://github.com/everypolitician/rebuilder
  - [x] https://github.com/everypolitician/pull_request_preview
  - [x] https://github.com/everypolitician/everypolitician-gender-summary
  - [x] https://github.com/everypolitician/rebuilder-ui
  - [x] https://github.com/everypolitician/ocd_lookup
  - [x] https://github.com/everypolitician/pull_request_cleaner
  - [x] https://github.com/everypolitician/image_cache
  - [x] https://github.com/everypolitician/combine_popolo_memberships
  - [x] https://github.com/everypolitician/zimbabwe-images
  - [x] https://github.com/everypolitician/twitter_username_extractor
  - [x] https://github.com/everypolitician/kuvakazim_updater
  - [x] https://github.com/everypolitician/parlparse-webhook-receiver
  - [x] https://github.com/everypolitician/parlparse-to-csv

**Comment by tmtmtmtm** [comment]
superseded by #492
