### ISSUE TITLE
TODO w/c 2016-08-30

### ISSUE THREAD

**Issue by octopusinvitro** [everypolitician/everypolitician#492]
This week:

@ondenman @octopusinvitro
## Legislature Pages

Check here for the right order to cover these: [release house and house/download pages #15256](https://github.com/everypolitician/viewer-sinatra/issues/15256)
- [x]  :smile:  Add a legislature/download page (https://github.com/everypolitician/viewer-sinatra/pull/15245)
  - [x]  :smiley: Remove term collapse from download page (https://github.com/everypolitician/viewer-sinatra/issues/15243#event-772000424)
- [x]  :smiley: Page for each legislature (https://github.com/everypolitician/viewer-sinatra/pull/15246)
- [x] :smile: Simplify `term_table_url` ([15241](https://github.com/everypolitician/viewer-sinatra/issues/15241))   (https://github.com/everypolitician/viewer-sinatra/pull/15251)
- [x] :smile: Rename route slugs for consistency  (https://github.com/everypolitician/viewer-sinatra/pull/15247)
- [x] :smile: Link to house from house/download (https://github.com/everypolitician/viewer-sinatra/pull/15339)
- [x] :smile:  Link to house/download on the country page download buttons (https://github.com/everypolitician/viewer-sinatra/pull/15255)
- [ ]  Improve text about "other politicians in same country" at bottom of house page (https://github.com/everypolitician/viewer-sinatra/issues/15259) :construction: :eyes: [~~#15426~~](https://github.com/everypolitician/viewer-sinatra/pull/15426) (https://github.com/everypolitician/viewer-sinatra/pull/15451)
- [x] :smile:  link to Legislature page from Term Table page (header bar)
- [ ] Delete the country/download template and redirect to country :construction: :eyes: ~~(https://github.com/everypolitician/viewer-sinatra/pull/15261)~~ ( [#15464](https://github.com/everypolitician/viewer-sinatra/pull/15464) and [#15466](https://github.com/everypolitician/viewer-sinatra/pull/15466))
## Refactoring
- [ ] Remove ABC override ([15249](https://github.com/everypolitician/viewer-sinatra/issues/15249))
  - [ ] person_memberships 🚧 💥 
  - [ ] group_date 🚧 💥 
  - [ ] percentages 🚧 :eyes:

@mhl 
- [ ] [Remove UK data dependency on PopIt](https://github.com/everypolitician/everypolitician-data/issues/16236)
- [ ] python port of EveryPolitician-ruby

@davewhiteland 
- [ ] Document Libraries https://github.com/everypolitician/everypolitician-docs/issues/23 :construction:
- [x] READMEs 
  - [x] https://github.com/everypolitician/everypolitician-popolo/issues/33
  - [x] https://github.com/everypolitician/everypolitician-ruby/issues/15
- [ ] Make Issues Templates
  - [x] Viewer-Sinatra
- [ ] Make PR Templates
  - [ ] Viewer-Sinatra
  - [ ] everypolitician-ruby
  - [ ] everypolitician-popolo

@chrismytton 
- [ ] Uganda Areas https://github.com/everypolitician/everypolitician-data/pull/12496
- [ ] Group UUIDs https://github.com/everypolitician/everypolitician/issues/428
- [ ] everypolitician-ruby additions (cross-dependency with [Docs#23](https://github.com/everypolitician/everypolitician-docs/issues/23))
- [ ] Cut heroku usage

**Comment by tmtmtmtm** [comment]
superseded by #496
