### ISSUE TITLE
TODO w/c 2016-09-05

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#496]
## [Broken Imports](https://github.com/everypolitician/everypolitician-data/labels/broken%20import)
- [x] 😃 US/House (2nd) ([PR](https://github.com/everypolitician/everypolitician-data/pull/16617)) 
- [ ] Germany/Bundestag (3rd) ([PR](https://github.com/everypolitician/everypolitician-data/pull/16622))  👀 
  - [x] :smiley: Map new IDs to existing UUIDs 
  - [x] Fix missing wikidata
- [ ] 👀 Australia/Representatives (4th) 👀 Latest [PR](https://github.com/everypolitician/everypolitician-data/pull/17134)
  - [x] :smiley: Scraper adds new term
  - [x] Scott Morrison missing wikidata
- [x] 😄 Australia/Senate (4th)
  - [x] :smiley: Scraper fixed ([PR](https://github.com/everypolitician-scrapers/australia-openaustralia-senators/pull/1))
  - [x] ~~:construction: New [PR](https://github.com/everypolitician/everypolitician-data/pull/16652) not fixed. Morph finished but didn't take the changes from scraper ([morph](https://morph.io/everypolitician-scrapers/australia-openaustralia-senators))~~  New term added in  latest [PR](https://github.com/everypolitician/everypolitician-data/pull/16956)
- [ ] ~~:question: India (9th) -- Wikidata ID no longer linked to on https://en.wikipedia.org/wiki/Yogi_Adityanath. Wikidata possibly broken? (https://www.wikidata.org/wiki/Q4683097) Name at top of page seems to be incorrect.~~ Wikidata page reverted to previous version. 👀 
- [ ] Malaysia (11th)
- [ ] :construction: Spain (15th)
  - [x] ~~:smiley: The missing contact details is because people were ceased. So we don't want their emails but we do want their twitter handlers. So I'm going back to my 2 months-old-never-merged PR to add those. [Old PR](https://github.com/everypolitician/everypolitician-data/pull/14239) -- [New PR 2-months-old](https://github.com/everypolitician/everypolitician-data/pull/14239) -- [New New PR](https://github.com/everypolitician/everypolitician-data/pull/16986)~~
  - [x] :smiley: revert only the source that's problematic (`morph/official-2015.csv`), get a clean PR, and merge it ([PR](https://github.com/everypolitician/everypolitician-data/pull/16939#commits-pushed-6880144))
  - [ ] fix the broken import
- [ ] :construction: Mexico (17th) 
  - [x] :smiley: Re-adding both official scrapers ([mexico-diputados](https://morph.io/everypolitician-scrapers/mexico-diputados) and [mexico-diputados-2015](https://morph.io/everypolitician-scrapers/mexico-diputados-2015)) to morph solved the issue. There were changes made in the official pages that were conflicting with the old data in the previous morph databases. 
  - [x] :smiley: New scraper for missing people: [morph](https://morph.io/everypolitician-scrapers/mexico-deputies-wikipedia-2015)
  - [x] :smiley: New scraper for wikidata including the previous scraper: [morph](https://morph.io/everypolitician-scrapers/mexico-deputies-wikidata)
  - [ ] ~~:construction: These are the changes after updating all the scrapers: [PR](https://github.com/everypolitician/everypolitician-data/pull/16664#commits-pushed-2f4717d).~~
  - [x] :smiley: Redid the whole thing. First revert the files that were causing problems ([PR](https://github.com/everypolitician/everypolitician-data/pull/16983#commits-pushed-6a1565e))
  - [ ] :eyes: Hardcode the urls of ceased membersin the scraper ([PR](https://github.com/everypolitician-scrapers/mexico-diputados-2015/pull/2))
  - [ ] :construction: Fix the files that are causing problems
- [ ] Mongolia (22nd) :eyes: [(PR)](https://github.com/everypolitician/everypolitician-data/pull/16971)
- [ ] :construction: Argentina (34th) 
  - [x] :smiley: Fix scraper ([PR](https://github.com/everypolitician-scrapers/argentina-diputados-wikidata/pull/1)).
  - [ ] :hourglass_flowing_sand: Waiting for morph to fix 255 error ([reported](https://help.morph.io/t/error-255-and-no-data/269))
- [ ] 😕 Poland (56th)   -- transient -- latest PR looks fine
  - [x] :disappointed: Reopened [#16404](https://github.com/everypolitician/everypolitician-data/issues/16404), as the problem seems to be back in [#16675](https://github.com/everypolitician/everypolitician-data/pull/16675)
  - [x] 😕 Looks like it cleared up again in [#16732](https://github.com/everypolitician/everypolitician-data/pull/16732)
- [ ] South Korea (58th)
- [x] :smiley: Romania (86th) 
- [x] :smiley: Venezuela (93rd) ([PR](https://github.com/everypolitician-scrapers/venezuela-asamblea-wikidata/pull/1))
- [X] :smiley:   Falkland Islands (158th) 
  - [X] :smiley:   ([PR](https://github.com/everypolitician/everypolitician-data/pull/16592))
- [ ] :eyes:  Dominican Republic (161st) 
  - [x] :smiley: Fix wikidata scraper ([PR](https://github.com/everypolitician-scrapers/dominican-republic-deputies-wikidata/pull/1))
  - [x] :smiley: Fix official scraper ([PR](https://github.com/everypolitician-scrapers/dominican-republic-deputies/pull/2))
  - [x] :smiley: Fix idmap mapping ([PR](https://github.com/everypolitician/everypolitician-data/pull/16587))
  - [ ] ~~:eyes:  Import: Use data from local run for 2016 and add manual file for 2010 ([PR](https://github.com/everypolitician/everypolitician-data/pull/16560))~~
  - [x] :smiley: Re-do previous PR. Split in two, use `git mv` to move the lost data into manual and check that no files were changed. ([PR](https://github.com/everypolitician/everypolitician-data/pull/17006))
  - [ ] :construction: Fix broken import
- [x] :smiley:  Tuvalu (168th) Please check out [this comment](https://github.com/everypolitician/everypolitician-data/issues/16430#issuecomment-245317119).
  - [x] :smiley:  Fixed ([PR](https://github.com/everypolitician/everypolitician-data/pull/16563#commits-pushed-c10a83d)) [New PR after re-adding scraper to morph](https://github.com/everypolitician/everypolitician-data/pull/16661#commits-pushed-3f6e78c)
  - [x] :smiley: Updated scraper ([PR](https://github.com/everypolitician-scrapers/tuvalu-parliament-wikipedia/pull/1))
- [x] :smiley: Guyana (190th) 
  - [x] :smiley: Fix missing gender/title info ([PR](https://github.com/everypolitician/everypolitician-data/pull/16581))
  - [x] :smiley: Fix name change in scraper ([PR](https://github.com/everypolitician-scrapers/guyana-parliament/pull/1))
  - [x] :smiley: Remove people with no titles from manual files ([PR prefix](https://github.com/everypolitician/everypolitician-data/pull/16774)) ([PR gender](https://github.com/everypolitician/everypolitician-data/pull/16773))
- [x] :smiley: Philippines ([Issue](https://github.com/everypolitician/everypolitician-data/issues/17205) & [PR](https://github.com/everypolitician/everypolitician-data/pull/17221))
- [x] :smiley:   Slovakia ([Issue](https://github.com/everypolitician/everypolitician-data/issues/17206)  & [PR](https://github.com/everypolitician/everypolitician-data/pull/17122))
- [x] :smiley:   Chile ([Issue](https://github.com/everypolitician/everypolitician-data/issues/17207))
- [x] :smiley: Belarus ([Issue](https://github.com/everypolitician/everypolitician-data/issues/17209) & [PR](https://github.com/everypolitician/everypolitician-data/pull/17161))
- [x] :smile:  Vanuatu
- [ ] 🚧 Denmark [PR](https://github.com/everypolitician/everypolitician-data/pull/17115)
## Taming the Rakefiles
- [ ] [Move Rakefile logic to libraries](https://github.com/everypolitician/everypolitician/issues/245)
  - [x] [stats.json](https://github.com/everypolitician/everypolitician-data/pull/16368)
    - [x] [Identifiers method](https://github.com/everypolitician/everypolitician-popolo/issues/53)
  - [ ] names.csv
  - [ ] [terms-*.csv](https://github.com/everypolitician/everypolitician/issues/320) 
  - [ ] positions.csv
### everypolitician-popolo
- [ ] [No dynamically created methods](https://github.com/everypolitician/everypolitician-popolo/issues/54)
  - [ ] [use true test data](https://github.com/everypolitician/everypolitician-popolo/issues/42)
  - [ ] All public methods documented

**Comment by tmtmtmtm** [comment]
@chrismytton I think your top priority has to be https://github.com/everypolitician/everypolitician/issues/449, and other ways to use less Heroku time.

We're only midway through day 3, and are already at 19% usage for the month.

**Comment by tmtmtmtm** [comment]
superseded by https://github.com/everypolitician/everypolitician/issues/505
