### ISSUE TITLE
Priorities w/c 2016-09-19

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#505]
- [ ] https://github.com/everypolitician/scraped_page_archive/issues/38 scraped-page-archive failing for DK
- [ ] :eyes: https://github.com/everypolitician/viewer-sinatra/pull/15433 missing closing tag
- [ ] :construction: https://github.com/everypolitician/viewer-sinatra/issues/14817 VS warnings from tests
- [ ] :construction: https://github.com/everypolitician/everypolitician/projects/2 rebuild viewer-static on EP-data merge
- [ ] :construction: https://github.com/everypolitician/everypolitician-popolo/issues/40 term.people
- [ ] :construction: https://github.com/everypolitician/everypolitician-popolo/issues/54 EP-popolo real methods
  - [x] [Events](https://github.com/everypolitician/everypolitician-popolo/pull/56)
- [ ] https://github.com/everypolitician/everypolitician/issues/245 post-Popolo file generation
  - [x] term-*.csv: https://github.com/everypolitician/everypolitician-data/pull/17335
  - [ ] names.csv
  - [ ] positions.json
## Data Issues
- [Broken Imports](https://github.com/everypolitician/everypolitician-data/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3A%22broken+import%22) (~~20~~ 23)
- Broken Scrapers
  - [tmtmtmtm](https://morph.io/tmtmtmtm/) (26)
  - [everypolitician-scrapers](https://morph.io/everypolitician-scrapers) (3)
  - [struan](https://morph.io/struan) (1)
- [New Terms](https://docs.google.com/spreadsheets/d/1t2rG77jLOlvhXRjE_35bHa46c0TJTLpOabvAl1mAUp8/edit#gid=1973956966) (31)
## Done
- [x] https://github.com/everypolitician/everypolitician/issues/486 rebuild by slug, not path
- [x] https://github.com/everypolitician/viewer-sinatra/issues/6332 top identifiers per person
- [x] Wikisnakker: don't blow up on missing data https://github.com/everypolitician/wikisnakker/pull/47
- [x] EveryPolitician::Popolo search indexes https://github.com/everypolitician/everypolitician-popolo/issues/64
- [ ] New Terms:
  - [x] [Australia](https://github.com/everypolitician/everypolitician-data/pull/17589)
- [x] Rollbar errors: 
  - [x] Latvia
  - [x] Vietnam
- [ ] Fix Broken Scrapers:
  - [x] [brasil-deputados-wikidata scraper](https://morph.io/tmtmtmtm/brasil-deputados-wikidata)
  - [x] [cook-islands-elections-wikipedia](https://morph.io/tmtmtmtm/cook-islands-elections-wikipedia)
  - [x] [aruba-parlamento](https://morph.io/tmtmtmtm/aruba-parlamento) (and add scraped-page-achive)
  - [x] [dominican-republic-deputies-wikidata](https://morph.io/everypolitician-scrapers/dominican-republic-deputies-wikidata)
  - [x] [isle-of-man-house-of-keys-wikipedia](https://morph.io/tmtmtmtm/isle-of-man-house-of-keys-wikipedia)
  - [x] [czech-chamber-of-deputies-wikidata](https://morph.io/tmtmtmtm/czech-chamber-of-deputies-wikidata)
- [ ] Fix Broken imports
  - [x] [Argentina (Senate)](https://github.com/everypolitician/everypolitician-data/pull/17524)
  - [x] [Italy (Senate)](https://github.com/everypolitician/everypolitician-data/pull/17496)
  - [x] [Romania](https://github.com/everypolitician/everypolitician-data/pull/17474)
  - [x] [Cook Islands](https://github.com/everypolitician/everypolitician-data/pull/17527)
  - [x] [Colombia (Senate)](https://github.com/everypolitician/everypolitician-data/pull/17583)
  - [x] [Isle of Man](https://github.com/everypolitician/everypolitician-data/pull/17587)

**Comment by tmtmtmtm** [comment]
followed by https://github.com/everypolitician/everypolitician/issues/515
