### ISSUE TITLE
Make MozFest flyer code sample work

### ISSUE THREAD

**Issue by struan** [everypolitician/everypolitician#529]
# Problem

There's a snippet of code included in our MozFest flyer that represents a where we'd like to be rather than where we are:

``` ruby
legislature = EveryPolitician::Index.new.country('Ecuador').lower_house
legislature.latest_term.memberships.each do |m|
  puts "#{m.person.name} (#{m.party.name}): @#{m.person.twitter || '?'}"
end
```

We need to update everypolitician-ruby and everypolitician-popolo to make this work.
# Proposed Solution

The following tickets need to be completed before MozFest:
- [x] https://github.com/everypolitician/everypolitician-ruby/issues/61 (`lower_house` method)
- [x] https://github.com/everypolitician/everypolitician-popolo/issues/79 (`party` accessor)
- [x] https://github.com/everypolitician/everypolitician-popolo/issues/77 (`latest_term.memberships`)
- [x] https://github.com/everypolitician/everypolitician-ruby/issues/66 (`legislature.latest_term`)
- [x] https://github.com/everypolitician/everypolitician-popolo/issues/116 (`terms.find_by` in `legislature.latest_term`)
- [ ] https://github.com/everypolitician/everypolitician-popolo/issues/105 (membership subclasses)

The last of these isn't strictly required.
- [x] Release updated everypolitician-popolo to RubyGems
- [x] Release updated everypolitician-ruby to RubyGems
# Acceptance Criteria

The code snippet above works.
# Due Date

27th October 2016 (day before MozFest)
# Bloggable?

Flyer driven development!

**Comment by struan** [comment]
Party accessor closed in https://github.com/everypolitician/everypolitician-popolo/commit/b3889831cfa8c9a627d3fcd593d6e69860ee1dcd

**Comment by struan** [comment]
`term.memberships` closed in https://github.com/everypolitician/everypolitician-popolo/commit/51ae1d0d89c79353e140627e7273ad290ea6de9d

**Comment by chrismytton** [comment]
everypolitician-popolo v0.8.0 released to [RubyGems](https://rubygems.org/gems/everypolitician-popolo/versions/0.8.0), and the [CHANGELOG entry is here](https://github.com/everypolitician/everypolitician-popolo/blob/40dc460d8340df9ae78469b755ce73b4fd074ce3/CHANGELOG.md#080---2016-10-28).

**Comment by chrismytton** [comment]
everypolitician v0.20.0 released to [RubyGems](https://rubygems.org/gems/everypolitician/versions/0.20.0), [CHANGELOG entry](https://github.com/everypolitician/everypolitician-ruby/blob/db003c0d1fdbe3f808ab8c43d165c765b1e6c82e/CHANGELOG.md#0200---2016-10-28).

**Comment by chrismytton** [comment]
OK I think this is all done now. Thanks for all your hard work on this @struan!
